### ISSUE TITLE
integrate DLEq into protocol

### ISSUE THREAD

**Issue by noot** [noot/atomic-swap#63]
to save on gas, a secp256k1 ScalarBaseMult can occur in the swap contract instead of a ed25519 ScalarBaseMult to verify the secret corresponding to the public key, as this is cheaper to do with secp256k1. a DLEq proof can be used to then verify that the ed25519 public key and secp256k1 public key correspond to the same secret scalar. this needs to be provided by both Alice and Bob parties, as both their public keys are stored in the contract.

to perform this integration:
- swap contract needs to be updated to perform a secp256k1 ScalarBaseMult
- Alice needs to store the secp256k1 keys in the contract instead of the ed25519 keys
- both parties must generate a secp256k1 key as well as an ed25519 key in the keygen step of the protocol
- DLEq proof also needs to be generated in the keygen step of the protocol
- the proof needs to be verified in the handling of `SendKeysMessage`, and the swap aborted if it isn't valid

**Comment by Lederstrumpf** [comment]
Of what's listed above, all but the integration into `SendKeysMessage` has already been completed during our hackathon in https://github.com/noot/atomic-swap/pull/4 - it's even serialized efficiently (64898 bytes), and also already includes the proof of knowledge mentioned by @kayabaNerve here: #60 (only improvement I can see so far would be stripping the ECDSA sig, which will save you 64 bytes + serialization overhead, if any).

Right now, the DLEQ proof is shared via a local file (`dleq_proof.dat`), which must of course be replaced, and the proof verification is handled via an external binary, which is not ideal. But if you integrate the serialized proof payload into the `SendKeysMessage` (which will then already work), I will make time to switch from the external binary to using FFI bindings for the DLEQ proof generation & verification. I believe what @alxs did here #27 will reduce effort too.

**Comment by Lederstrumpf** [comment]
another argument for going Rust FFI: @kayabaNerve's [dleq lib](https://github.com/kayabaNerve/dleq-rs/tree/develop) has had a lot of thought put into abstracting different curves - I haven't properly reviewed it yet, but once I'm no longer swamped with other work, I'll integrate it into Farcaster too & adjust the FFI bindings here as well.

**Comment by kayabaNerve** [comment]
Lack of peer review is why it's still branched, at which point I'll publish it as a proper crate. If you write a new one in Go (briefly mentioned), I'd be happy to write tests running the two proofs against each other so we can define another implementation of a consistent protocol.

**Comment by noot** [comment]
@Lederstrumpf okay awesome, I can pick up on that work integrating it into the Go side. I'll also look into the FFI/CGO route and see what it'll entail exactly. I'll message you once the Go integration is done, then we can work on that. if that doesn't go well I'll probably try to port @kayabaNerve 's implementation to Go, briefly looking at the library, it seems it should be doable without too much pain.
